config/routes.rb
Depot::Application.routes.draw do

  resources :names 
  resources :payment_details
  

  resources :products

  resources :eas_types
  
  resources :line_items

  resources :carts
  
  get "store/index"

  
    get 'admin' => 'admin#index'
     controller :sessions do
        get 'login' => :new
        post 'login' => :create
       delete 'logout' => :destroy
       end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"
  

  

root :to => 'store#index', :as => 'store'

end

app/models/name.rb
class Name < ActiveRecord::Base
  attr_accessible :YF_campout, :age, :eck_id, :hi_conf, :name, :seminar, :total
  validates :YF_campout,  :numericality => true
  validates :age, :numericality => true
  validates_presence_of :eck_id, :length => { :maximum => 12 }
  validates :hi_conf, :numericality => true
  validates_presence_of :name, :length => { :maximum => 30 }, :exclusion => { :in => %w(admin superuser) }
  validates :seminar, :numericality => true
  validates :total, :numericality => true
  
  has_one :payment_detail
  has_one :cart
  has_many :eas_types
  has_many :line_items
  
  def total_of_donations
       @sum_seminar = :hi_conf + :seminar
       @sum_all = :hi_conf + :seminar + :YF_campout
   end
  
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  # GET /names
  # GET /names.json
  def index
    @names = Name.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @names }
    end
  end

  # GET /names/1
  # GET /names/1.json
  def show
    @name = Name.find(params[:id])
        
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/new
  # GET /names/new.json
  def new
    @name = Name.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(params[:name])
    
    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render json: @name, status: :created, location: @name }
      else
        format.html { render action: "new" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /names/1
  # PUT /names/1.json
  def update
    @name = Name.find(params[:id])

    respond_to do |format|
      if @name.update_attributes(params[:name])
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name = Name.find(params[:id])
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="suggested_donations">
  <!-- Get this data from eas_types table -->
  </div>
  
  
  <div class="field_name">
    Your first and last name<br />
    <%= f.text_field :name %>
  </div>
  <div class="field_eckid">
    Current ECK Membership number<br />
    <%= f.text_field :eck_id, :size =>12 %>
  </div>
  <div class="field_age">
    Age<br />
    <%= f.number_field :age, as: :string, :size => 3 %>
  </div>
  <div class="payment_notes"><br/>
  ** Please enter whole dollar values **
  </div>
  <div class="field_seminar">
    Seminar Donation <br />
    <%= f.number_field :seminar %>
  </div>
  <div class="field_hiconf">
    HI Conference Donation<br />
    <%= f.number_field :hi_conf %>
  </div>
  <div class="field_yfcampout">
    Payment for Youth/family camp  out<br />
    <%= f.number_field :YF_campout %>
  </div>
  <div class="field_total">
    Total donation <br />
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<h1>Listing Attendees Names</h1>
/views/names/index.html.erb

<table>
  <tr>
    <th>Name</th>
    <th>Eck Id#</th>
    <th>Age</th>
    <th>Seminar</th>
    <th>Hi Conf</th>
    <th>Campout</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= name.name %></td>
    <td><%= name.eck_id %></td>
    <td><%= name.age %></td>
    <td><%= name.seminar %></td>
    <td><%= name.hi_conf %></td>
    <td><%= name.YF_campout %></td>
    <td><%= name.total %></td>
    <td><%= link_to 'Show', name %></td>
    <td><%= link_to 'Edit', edit_name_path(name) %></td>
    <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Name', new_name_path %>

app/views/names/new.html.erb
<h1>Name of person for Registration</h1>
<p>
The H.I. Conference includes a light lunch and afternoon tea.<br/>
Campout forms must be completed and returned by 14th December 2011, as places are limited.<br/>
 Your email address is requested for Youth Program and Campout registrations.<br/>
Current ECKANKAR ID will be required for some sessions.
</p>
<p>
Please enter the registration details one at a time for each person in your family or group
</p>

<%= render 'form' %>

<%= link_to 'Edit', new_name_path(@name) %>
<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @name.name %>
</p>

<p>
  <b>Eck Id#:</b>
  <%= @name.eck_id %>
</p>

<p>
  <b>Age:</b>
  <%= @name.age %>
</p>

<p>
  <b>Seminar:</b>
  <%= @name.seminar %>
</p>

<p>
  <b>Hi conf:</b>
  <%= @name.hi_conf %>
</p>

<p>
  <b>Yf campout:</b>
  <%= @name.YF_campout %>
</p>

<p>
  <b>Total:</b>
  <%= @name.total %>
</p>

<%= link_to 'New Name', new_name_path %> | 
<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>