config/routes.rb
Depot::Application.routes.draw do

  resources :names 
  resources :payment_details
  

  resources :products

  resources :eas_types
  
  resources :line_items

  resources :carts
  
  get "store/index"

  
    get 'admin' => 'admin#index'
     controller :sessions do
        get 'login' => :new
        post 'login' => :create
       delete 'logout' => :destroy
       end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"
  

  

root :to => 'store#index', :as => 'store'

end

app/models/payment_detail.rb
class PaymentDetail < ActiveRecord::Base
  attr_accessible :Donation, :Name_on_Card, :address, :card_number, :country, :email, :expiry_date, :pay_by, :pcode, :state, :suburb

  
  validates_presence_of :Donation, :numericality => true
  validates_presence_of :Name_on_Card, :length => { :maximum => 30 }
  validates_presence_of :address, :country, :locality, :phone, :postcode, :state, :presence =>true
  validates :card_number, :presence => {:message => 'card number: 0000 0000 0000 0000.'}
  validates_presence_of :country, :length => { :maximum => 15 }
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates_presence_of :expiry_date, :length => { :maximum => 8 }
  validates_presence_of :pay_by, :presence => {:message => 'Payment Method: Visa, Mastercard, etc.'}
  validates :pcode, :length => { :maximum => 16 }, :numericality => true
  validates_presence_of :state, :length => { :maximum => 10 }, :exclusion => { :in => %w(admin superuser) }
  validates :suburb, :length => { :maximum => 30 }, :exclusion => { :in => %w(admin superuser) }
  
  belongs_to :name
  has_many :names, :dependent => :destroy
  has_one :cart
  has_many :eas_types
  has_many :line_items

end

app/controllers/payment_details_controller.rb
class PaymentDetailsController < ApplicationController
  # GET /payment_details
  # GET /payment_details.json
  def index
    @payment_details = PaymentDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_details }
    end
  end

  # GET /payment_details/1
  # GET /payment_details/1.json
  def show
    @payment_detail = PaymentDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_detail }
    end
  end

  # GET /payment_details/new
  # GET /payment_details/new.json
  def new
    @payment_detail = PaymentDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_detail }
    end
  end

  # GET /payment_details/1/edit
  def edit
    @payment_detail = PaymentDetail.find(params[:id])
  end

  # POST /payment_details
  # POST /payment_details.json
  def create
    @payment_detail = PaymentDetail.new(params[:payment_detail])

    respond_to do |format|
      if @payment_detail.save
        format.html { redirect_to @payment_detail, notice: 'Payment detail was successfully created.' }
        format.json { render json: @payment_detail, status: :created, location: @payment_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_details/1
  # PUT /payment_details/1.json
  def update
    @payment_detail = PaymentDetail.find(params[:id])

    respond_to do |format|
      if @payment_detail.update_attributes(params[:payment_detail])
        format.html { redirect_to @payment_detail, notice: 'Payment detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_details/1
  # DELETE /payment_details/1.json
  def destroy
    @payment_detail = PaymentDetail.find(params[:id])
    @payment_detail.destroy

    respond_to do |format|
      format.html { redirect_to payment_details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payment_details_helper.rb
module PaymentDetailsHelper
end

app/views/payment_details/_form.html.erb
<%= form_for(@payment_detail) do |f| %>
  <% if @payment_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_detail.errors.count, "error") %> prohibited this payment_detail from being saved:</h2>

      <ul>
      <% @payment_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_address">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field_suburb_state_pcode">
    <%= f.label :suburb %> ................<%= f.label :state %> .............. <%= f.label :pcode %><br/>
    <%= f.text_field :suburb, :size => 15 %>
    <%= f.text_field :state, :size =>12 %>
    <%= f.text_field :pcode, :size =>8 %>
  </div>
  <div class="field_country_and_email">
    <%= f.label :country %> ........... <%= f.label :email %><br />
    <%= f.text_field :country, :size =>12 %>
    <%= f.text_field :email %>
  </div>
  <hr>
  <div class="field_payby">
  Copy and paste one of these into the field<br/>
    Visa . Mastercard . Bank Transfer
    
    <%= f.text_field :pay_by, :size =>12 %>
  </div>
  <div class="field">
    <%= f.label :card_number %> or Transfer number . 
    <%= f.text_field :card_number %>
  </div>
  <div class="field_expdate">
    Card <%= f.label :expiry_date %> . . . . . . . . . . . .
    <%= f.text_field :expiry_date, :size =>10 %>
  </div>
  <div class="field_name_on_card">
    <%= f.label :Name_on_Card %> . . . . . . . . . . . . . . 
    <%= f.text_field :Name_on_Card %>
  </div>
  <hr>
  <div class="field_donation">
    Your Total <%= f.label :Donation %>$ 
    <%= f.number_field :Donation, :size =>4 %>
  </div>
  <p> </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_details/edit.html.erb
<h1>Editing payment detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_detail %> |
<%= link_to 'Back', payment_details_path %>

app/views/payment_details/index.html.erb
<h1>Listing payment details</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Suburb</th>
    <th>State</th>
    <th>Pcode</th>
    <th>Country</th>
    <th>Email</th>
    <th>Pay by</th>
    <th>Card number</th>
    <th>Expiry date</th>
    <th>Name on card</th>
    <th>Donation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_details.each do |payment_detail| %>
  <tr>
    <td><%= payment_detail.address %></td>
    <td><%= payment_detail.suburb %></td>
    <td><%= payment_detail.state %></td>
    <td><%= payment_detail.pcode %></td>
    <td><%= payment_detail.country %></td>
    <td><%= payment_detail.email %></td>
    <td><%= payment_detail.pay_by %></td>
    <td><%= payment_detail.card_number %></td>
    <td><%= payment_detail.expiry_date %></td>
    <td><%= payment_detail.Name_on_Card %></td>
    <td><%= payment_detail.Donation %></td>
    <td><%= link_to 'Show', payment_detail %></td>
    <td><%= link_to 'Edit', edit_payment_detail_path(payment_detail) %></td>
    <td><%= link_to 'Destroy', payment_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment detail', new_payment_detail_path %>

app/views/payment_details/new.html.erb
<h1>New payment </h1>

<%= render 'form' %>

<%= link_to 'Back', payment_details_path %>

app/views/payment_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @payment_detail.address %>
</p>

<p>
  <b>Suburb:</b>
  <%= @payment_detail.suburb %>
</p>

<p>
  <b>State:</b>
  <%= @payment_detail.state %>
</p>

<p>
  <b>Pcode:</b>
  <%= @payment_detail.pcode %>
</p>

<p>
  <b>Country:</b>
  <%= @payment_detail.country %>
</p>

<p>
  <b>Email:</b>
  <%= @payment_detail.email %>
</p>

<p>
  <b>Pay by:</b>
  <%= @payment_detail.pay_by %>
</p>

<p>
  <b>Card number:</b>
  <%= @payment_detail.card_number %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @payment_detail.expiry_date %>
</p>

<p>
  <b>Name on card:</b>
  <%= @payment_detail.Name_on_Card %>
</p>

<p>
  <b>Donation:</b>
  <%= @payment_detail.Donation %>
</p>


<%= link_to 'Edit', edit_payment_detail_path(@payment_detail) %> |
<%= link_to 'Back', payment_details_path %>